[tool.black]
line-length = 119
target-version = ['py39']

[tool.ruff]
# Never enforce `E501` (line length violations).
ignore = ["C901", "E501", "E741"]
select = ["C", "E", "F", "I", "W"]
line-length = 119

# Ignore import violations in all `__init__.py` files.
[tool.ruff.per-file-ignores]
"*.py" = ["E402"]
"__init__.py" = ["F401", "F403", "F811"]

[tool.ruff.isort]
lines-after-imports = 2
known-third-party = ["jax","flax","jaxtyping","transformers"]
